default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements


  - repo: local
    hooks:
      - id: isort
        name: Isort
        entry: isort .
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff_c
        name: Ruff check
        entry: ruff check --fix
        language: system
        types: [ python ]
        pass_filenames: false
