[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "url_shortener"
version = "0.1"

[tool.ruff]
line-length = 79
src = ["src"]

[tool.isort]
line_length = 88
